### ISSUE TITLE
Host migration bug

### ISSUE THREAD

**Issue by AeonLucid** [AeonLucid/Impostor#5]
When a match is finished and some players have pressed "play again", if the hosts leaves the game gets stuck.

**Comment by GerardSmit** [comment]
This also happens when the host is kicked out of the lobby.

**Reproduction**
1. Start a game.
2. Call the button for an emergency.
3. Kick the host from the lobby (you can find this in the chat menu by clicking ![image](https://user-images.githubusercontent.com/2109929/94350372-feaa7d80-004d-11eb-9da1-608095fedb5c.png) and then clicking ![image](https://user-images.githubusercontent.com/2109929/94350316-67ddc100-004d-11eb-97a8-fc807cf95770.png)).
4. The voting will never end, you're stuck in the voting screen ([Screenshot](https://user-images.githubusercontent.com/2109929/94350411-5b0d9d00-004e-11eb-81d7-27539ad0b6d6.png)).
